### PR TITLE
Fix error with Babel 7

### LINKED ISSUE #5: Not working with Babel7
After upgrading to babel 7, I am getting the following error:
`TypeError: Cannot read property 'sourceFileName' of undefined`

### PR DESCRIPTION
**Pull request by ecerroni**
Fixes #5

### CODE REVIEW

**Comment by madshall** [comment]
Thank you!

**Comment by madshall** [comment]
One question - is it backwards compatible?

**Comment by ecerroni** [comment]
Mmh, I don't know. To be honest I did not take the time to look into it and see if it would have worked with Babel6 too. Sorry for that.

**Comment by madshall** [comment]
Np, I'll bump the major version to be safe

**Pull request merged**
